
name = "bsky-bridge"
main = "src/worker.js"
compatibility_date = "2024-03-01"
workers_dev = true

[triggers]
crons = ["*/5 * * * *"]

[vars]
BLUESKY_HANDLE = "project-grimoire.dev"

[[kv_namespaces]]
binding = "KV"
id = "6b7e1498777d4783a8fa9dda02e4d38e"

[observability]
	[observability.logs]
	enabled = true
	invocation_logs = true
