
name = "bsky-bridge"
main = "src/worker.js"
compatibility_date = "2024-03-01"
workers_dev = true

[triggers]
crons = ["*/5 * * * *"]

[vars]
APP_URL = "https://bsky-bridge.project-grimoire.dev"
EMAIL_VERIFICATION_ENABLED = "true"
MAX_ACCOUNTS = "50"
MAINTENANCE_MODE = "false"

[[kv_namespaces]]
binding = "KV"
id = "6b7e1498777d4783a8fa9dda02e4d38e"

[[d1_databases]]
binding = "DB"
database_name = "bsky-bridge"
database_id = "c6ea1c83-3e9e-4359-93a6-e0d140348bf8"
migrations_dir = "migrations"

[[queues.producers]]
binding = "QUEUE"
queue = "bsky-bridge-queue"

[[queues.consumers]]
queue = "bsky-bridge-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3

[observability]
	[observability.logs]
	enabled = true
	invocation_logs = true
